### PR TITLE
非常好！

### PR DESCRIPTION
**Pull request by BigBaiBrother**
看了好几天了，对于一个刚工作的小白来说，看到这个非常详细的权限使用，感觉非常棒，很详细，我在网上找了很多，但是都不详细，本来计划使用简书上那个跳转到设置页面的了，但是又看到了您的这篇，顿时感觉世界充满了爱！

### CODE REVIEW

**Comment by samtstern** [comment]
@BigBaiBrother could you explain the purpose of this pull request?  It's not clear from the commit messages and I don't speak Chinese ;-)

**Comment by VBallack** [comment]
@samtstern He said that he is an android beginner, so  I do not think he want to  pull request, maybe it is just a mistake. The Chinese means "Thank you!!!"

**Comment by samtstern** [comment]
@VBallack thanks for clarifying.
@BigBaiBrother I am going to close this because I think it's an accidental pull request.

**Comment by BigBaiBrother** [comment]
@VBallack @baiiu @samtstern Really，I'm not to pull a request, I'm so thankful to all of you.

**Comment by baiiu** [comment]
@samtstern @BigBaiBrother @VBallack 
Thanks for you all, this pull request is an accident of sure, I don't mean to do this as well.

And Your `easypermissions` is pretty good so that makes the permission in Android M become so clear and easy to control and all of circumstances are considered about.I forked this and do a little change because I think it maybe work better without using annotations, which makes it more easier to use.

**Pull request closed without merging**
