### PR TITLE
Simpler Permission in BaseActivity

### PR DESCRIPTION
**Pull request by tsy12321**
Update：
1. Simpler Permission in BaseActivity
2. add Chinese README

Look forward to your reply.

### CODE REVIEW

**Comment by samtstern** [comment]
@tsy12321 two things:

1. What do you mean by "simpler permission"?
2. I can't add a chinese language README because I am unable to maintain it (I don't speak Chinese).  If you know of a good chinese guide to this library I am happy to link it.

**Comment by samtstern** [comment]
Hi @tsy12321 thanks for the contribution!  A few things.

1. I can't accept the chinese README (although I appreciate it) because I don't speak Chinese so I am unable to review or maintain it.  However if you posted it in a blog post or a fork I would be happy to link to it from the README here.

2. I don't think the `performWithPermission` model is a good fit for this library, however I do think it's a useful recipe.  It's something that is better explained but not actually added to the core library code.

**Comment by tsy12321** [comment]
Thanks for your reply！It is my first pr!
I fork it with Chinese README and look forwark you to link it in your 'easypermission'. (https://github.com/tsy12321/easypermissions).
In addition, `performWithPermission ` in it. I want it can help somebody. I love open source.

PS: Forgive me have poor Engilish，I‘m trying to learn it.

**Comment by samtstern** [comment]
@tsy12321 thanks again for the PR, your english is pretty good!

I would prefer to link to a README that is simply translated to chinese with no other changes.  The README in your fork contains `performWithPermission` which is different than this library, and there could be more changes over time.

**Comment by tsy12321** [comment]
That's all right. 
I would change it over time. Some custom feature.
This chat is very happy! Thanks so much.

**Pull request closed without merging**
