### PR TITLE
Fix the dependencies statement.

### PR DESCRIPTION
**Pull request by ligboy**

### CODE REVIEW

**Comment by samtstern** [comment]
@ligboy I don't believe the `@aar` suffix is needed, could you explain why you want to add it?

**Comment by msisinni** [comment]
Without the `@aar`, I am told 
```
Could not find easypermissions.jar (pub.devrel:easypermissions:0.1.9).
  Searched in the following locations:
      https://jcenter.bintray.com/pub/devrel/easypermissions/0.1.9/easypermissions-0.1.9.jar
```

**Comment by samtstern** [comment]
Do you get the same error for 0.1.8?  I want to determine if this is a new
issue with the 0.1.9 release.

**Comment by msisinni** [comment]
No, I do not get the same error for 0.1.8. My guess is the pom file in [https://jcenter.bintray.com/pub/devrel/easypermissions/0.1.8](url) is just pointing the line 
`compile 'pub.devrel:easypermissions:0.1.8'` the aar file in the same directory. Not having the pom file in 0.1.9 means we need to specify the aar in gradle.

**Comment by ligboy** [comment]
I signed it!

**Comment by ligboy** [comment]
You should post `easypermissions-0.1.9.jar` to bintray. Without the `easypermissions-0.1.9.jar`, you need add @aar suffix.

**Comment by samtstern** [comment]
See #34 which is now fixed, this should not be necessary anymore.

**Pull request closed without merging**
