### PR TITLE
add autoRequestPermission() API 

### PR DESCRIPTION
**Pull request by LeonChen1024**
as usually if app don't have permission we need to request permission,so this API will easy to use.

### CODE REVIEW

**Comment by LeonChen1024** [comment]
I signed it!

**Comment by SUPERCILEX** [comment]
This actually already exists! The request perms method takes a callback that will be notified immediately if the permission has already been granted.

**Comment by LeonChen1024** [comment]
@SUPERCILEX 
```java
@AfterPermissionGranted(RC_LOCATION_CONTACTS_PERM)
    public void locationAndContactsTask() {
        if (hasLocationAndContactsPermissions()) {
            // Have permissions, do the thing!
            Toast.makeText(this, "TODO: Location and Contacts things", Toast.LENGTH_LONG).show();
        } else {
            // Ask for both permissions
            EasyPermissions.requestPermissions(
                    this,
                    getString(R.string.rationale_location_contacts),
                    RC_LOCATION_CONTACTS_PERM,
                    LOCATION_AND_CONTACTS);
        }
    }
```
In sample , we should use the API like that . I think that requesting permission when there is no permission is a very common situation，so ,if there is a API can do this make user avoid from the inconvenient `if else  `  is more easy to used.

**Comment by samtstern** [comment]
@LeonChen1024 thank you for sending this pull request.  In my opinion I don't believe the `if/else` form is inconvenient enough to make us add something like `autoRequest`.  In the future please open an issue before sending a PR for a new feature so that we can discuss it and save you time!

Thanks again for sending such a well-formed PR though!  Hope you understand the decision.

**Comment by LeonChen1024** [comment]
Thanks , I think i understand that ,   Sorry for wasting your time and never happen this mistake again.

**Comment by SUPERCILEX** [comment]
@LeonChen1024 Don't worry about it! 😊 BTW, here's what I meant when I said this already existed:
```java
public void start() {
    // This will call the annotation processor immediately if the permissions are granted, else request them
    EasyPermissions.requestPermissions(
            this,
            getString(R.string.rationale_location_contacts),
            RC_LOCATION_CONTACTS_PERM,
            LOCATION_AND_CONTACTS);
}

@AfterPermissionGranted(RC_LOCATION_CONTACTS_PERM)
public void locationAndContactsTask() {
    Toast.makeText(this, "TODO: Location and Contacts things", Toast.LENGTH_LONG).show();
}
```

**Comment by samtstern** [comment]
@LeonChen1024 definitely not a waste of our time!  It was an interesting proposal

**Pull request closed without merging**
