### PR TITLE
Add new methods to avoid showing rationale

### PR DESCRIPTION
**Pull request by carlphilipp**
Hello,

I added 2 public methods. The idea of that pull request is to provide a way to not show any rationale if we do not want any. In my case, in my app, I do not feel the need to have that message showing up. Any questions or comments?

Thank you,
Carl

### CODE REVIEW

**Comment by carlphilipp** [comment]
I signed it!

**Comment by samtstern** [comment]
@carlphilipp thanks for this contribution.  I understand your motivation here, but the goal of this library is to make it very simple for developers to follow the Android M permission guidelines.  Avoiding permission rational is not in the spirit of the guidelines, so I think adding this boolean option could negatively affect some user experiences.

I am going to close this PR.  In the future if you want to make a change like this it's always safer to discuss it in an Issue first so you don't have to go through all the work of writing the code before getting feedback.

**Comment by carlphilipp** [comment]
@samtstern, it's ok I understand, I will ask next time before doing any change. 

Also note that the boolean I added is in a private method, so it's not exposed to the developer. The two new methods exposed do not contain any rationale String, that's the only diff to the developer.

Thank you for taking the time to review it!

**Comment by aicaprio** [comment]
Hi,

I need these methods too， but i didn't saw it in version 0.4.
Is there any methods replaceable?

**Pull request closed without merging**
