### PR TITLE
Add a parameter for user to set a title to the dialog directing to the setting page.

### PR DESCRIPTION
**Pull request by kelv1nq1an**
For myself, it's better to set a title to this dialog which directing to the setting page.

### CODE REVIEW

**Comment by kelv1nq1an** [comment]
I signed it!

**Comment by jaibatrik** [comment]
What about backward compatibility?

**Comment by kelv1nq1an** [comment]
I have bring back the old two methods for backward compatibility. I am so embarrassed
 to forget it.

**Comment by samtstern** [comment]
@kelv1nq1an thanks for this contribution!  I have to think about how much overloading is desirable here, but this looks pretty good.

**Comment by samtstern** [comment]
@kelv1nq1an I really appreciate this contribution as it has made me think a lot about the API surface.  I am going to pursue something a little different here that I think will sastisfy your need while also keeping things tidy.

I will keep this PR open until I come up with something.

**Comment by samtstern** [comment]
@kelv1nq1an see #41 which changed this settings dialog to a `Builder` pattern.  This includes the ability to set the title without an exploding number of overloads.

**Pull request closed without merging**
