### PR TITLE
Updating project to support Android Studio 4.0

### PR DESCRIPTION
**Pull request by seventhmoon**

### CODE REVIEW

**Comment by samtstern** [comment]
@seventhmoon thanks for this PR!  I'd be happy to upgrade the project but looks like the tests are currently failing.  Once you get them to pass I can merge this.

**Comment by seventhmoon** [comment]
Oh. Some API is deprecated in Truth when upgrading from com.google.truth:truth:0.42 to com.google.truth:truth:1.0.1
Let me revert this change

**Comment by seventhmoon** [comment]
The RuntimeException seems is a known issue

> java.lang.RuntimeException: Unable to resolve activity for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=pub.devrel.easypermissions.test/pub.devrel.easypermissions.testhelper.TestActivity } -- see https://github.com/robolectric/robolectric/pull/4736 for details

**Comment by samtstern** [comment]
@seventhmoon nice the build passed!  Thanks for jumping on that so quickly.

**Pull request merged**
