### PR TITLE
Fix JaCoCo error

### PR DESCRIPTION
**Pull request by henriquenfaria**
- Migrate to gradle-android-junit-jacoco-plugin
- Update robolectric, shadows-supportv4 and mockito-core dependencies

### CODE REVIEW

**Comment by samtstern** [comment]
I see we're moving to a plugin by the one and only @vanniktech!  LGTM, will merge if green.

**Comment by henriquenfaria** [comment]
Travis builds are failing since August. This PR fixes that by using another jacoco plugin and updating our testing libraries.

**Comment by henriquenfaria** [comment]
> I see we're moving to a plugin by the one and only @vanniktech! LGTM, will merge if green.

It's green now :)

**Comment by samtstern** [comment]
Huh yeah you're right:
https://travis-ci.org/googlesamples/easypermissions/builds/448334619

I wonder why I never noticed the build failures!  Thanks for being on top of it.

**Comment by vanniktech** [comment]
My pleasure <3

**Pull request merged**
