### PR TITLE
DialogMixin for additional dialog configuration and customization.

### PR DESCRIPTION
**Pull request by dsokolov**
For example, you can make dialog non-cancelable or disallow closing on click outside.
It can solve issue #49.

### CODE REVIEW

**Comment by dsokolov** [comment]
I signed it!

**Comment by samtstern** [comment]
@dsokolov thanks for this contribution.  We are currently doing some pretty big changes to the dialog in #48 so that will probably conflict with this pretty heavily.

I would also prefer not to add any more arguments to existing methods as this library should have limited configuration options (it's meant to be "Easy" after all) and it's been growing over time.

I am definitely willing to consider non-cancelable as the default though, I agree with #49 that it is probably the best behavior.

**Comment by dsokolov** [comment]
@samtstern 
> not to add any more arguments to existing methods
It makes me a bit sad but of course EasyPermissions should stay easy. The only meaning of DialogMixin is keep present behavior and methods signatures, but adding non-cancelable ability.

> I am definitely willing to consider non-cancelable as the default though, I agree with #49 that it is probably the best behavior.
How soon do you plan to release #48 ? If not soon, can a make a simple pull-request makes all dialogs non-cancelalbe?

**Comment by samtstern** [comment]
@dsokolov I will release #48 as soon as it is merged, so I expect that to be today or tomorrow.  It looks like @k0shk0sh already added the non-cancelable behavior there so we're all set.

I am going to close this PR, thank you for raising this issue and being willing to contribute.

**Pull request closed without merging**
