### PR TITLE
New public method to verify if we should show the rationale dialog

### PR DESCRIPTION
**Pull request by lucmousinho**
Used to create my own rationale dialog

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@lucmousinho I think this method already exists: https://github.com/googlesamples/easypermissions/pull/92/files#diff-ebe31a7c2821276f776df6a2c727c9f0R397.

@samtstern If we make that method public, I think we should fix it up to have 3 overloads (Activity, and 2 Fragments) like what happened in #76.

**Comment by samtstern** [comment]
@lucmousinho if you know you're in an Activity you can call the AppCompat method directly:
`ActivityCompat.shouldShowRequestPermissionRationale(activity, perm);`

**Comment by lucmousinho** [comment]
@samtstern The method `shouldShowRequestPermissionRationale()` is used to verify just one permission. When I use the method `somePermissionPermanentlyDenied()`with a List of permissions it has every returned false to me, and testing the new method I can now make my own dialog to manage the rationale the way I want.

**Comment by lucmousinho** [comment]
I signed it!

**Comment by lucmousinho** [comment]
@SUPERCILEX and @samtstern , I added new methods with the 3 overloads and renamed it to `somePermissionDenied` , using a String array like the `requestPermissions` . 👍

**Comment by SUPERCILEX** [comment]
@samtstern is the repo owner here, but it LGTM!

**Comment by samtstern** [comment]
@lucmousinho sorry for the delay here but got no problem with adding these, merging!

**Pull request merged**
