### PR TITLE
Add a few features

### PR DESCRIPTION
**Pull request by mgolebiowski95**
- prevent rationale dialog from showing twice
- app settings dialog created based on dialog fragment
- now you have possibility to check app setting dialog is showing
- sample how prevent call EasyPermission.requestPermission(...) when android permission dialog is showing (too works after rotation changed)
- including kotlin

I sorry for using kotlin :-)

### CODE REVIEW

**Comment by mgolebiowski95** [comment]
I signed it

2018-01-12 11:43 GMT+01:00 googlebot <notifications@github.com>:

**Comment by samtstern** [comment]
@mgolebiowski95 thanks for sending this PR!  Looks like there's a lot going on here:

  1. Adding a sample in Kotlin, moving the Java sample
  2. Creating the `AbstractDialogFragment` class and using it for app settings dialogs
  3. Adding a new callback for when permissions are requested
  4. Prevent double-showing of the dialog (this one I am already doing in #195)

Can you explain your rationale for #2 and #3?  Also if we go forward with these we should probably split this into multiple pull requests as there are many unrelated things going on here.

**Comment by SUPERCILEX** [comment]
First off, thanks for the PR! For future reference, I'd recommend opening an issue first so we can discuss what features to add. Unfortunately, I see a few problems with this PR:
- Kotlin
  - I don't think we can include Kotlin in the library module yet because not everyone will be ready for a 1 MB increase in library size
  - As for the sample, not everyone will know kotlin so we still need to support the Java versions
- The bug fix to not show the dialog when it is already showing has been done by @samtstern: https://github.com/googlesamples/easypermissions/pull/195

Ask for your feature, could you show an example use case for how you would use it?

Thanks for your work!

**Comment by mgolebiowski95** [comment]
@SUPERCILEX yes, I shoud write this in issue section, sorry for that

@samtstern I know that you done fix #195, I append this to my code because I want test something before you have pushed the changes.

I only want dissolve one more problem with showing RationaleDialog under AppSettingDialog. 

In my uncommon case when I rotate phone / go to background -> come back to the app. 
like #193 clear application data -> grand first permission, other deny -> rotate phone a few times / go to background and come back to the app (RationaleDialog  show under AppSettingDialogdialog)

Now in library, AppSettingDialog isn't based on DialogFragment and I couldn't check is showing like RationaleDialog via 'getFragmentManager().findFragmentByTag(RationaleDialog .TAG) != null'

Other idea is, if library invoke method which shows AndroidPermissinoDialog (e.g. Activity.requestPermission(...)) callback move outside from library. It would be good to know if library will show AndroidPermissionDialog. Then would be possibility to save this state and wait for doing something else. I my case I want to know if the AndroidPermissionDialog is is shown.

I presented the idea how You can improve your library. Now I know that it would be better to append this issue to issue section.

**Comment by samtstern** [comment]
@mgolebiowski95 thanks for sharing your ideas!  I agree, let's discuss each of these individual things in an Issue and see if we can come up with a solution together.

I am going to close this PR so we can go with that plan.  We can always re-open it if we need to.

**Pull request closed without merging**
