### PR TITLE
replace List with varargs operator (...)

### PR DESCRIPTION
**Pull request by xanscale**

### CODE REVIEW

**Comment by samtstern** [comment]
@xanscale thanks for sending this PR.  Can you explain why you'd want this?  In my mind a List is more useful than varargs when getting a callback.

**Comment by xanscale** [comment]
@samtstern most of times user require 1 permission, inside somePermissionPermanentlyDenied is easyer

**Comment by samtstern** [comment]
@xanscale there already is a method `permissionPermanentlyDenied` that takes a single `String`.

**Comment by xanscale** [comment]
sorry, I did not see it. it would still be useful to have one method for both, or alternatively use the same method name. (to receive suggestions from Android studio)

**Comment by samtstern** [comment]
Thanks for the feedback.  I think you're right that using the same method name with varargs would have been better, but at this point I don't think it justifies the breaking API change for existing developers.

I'm going to close this PR as for now I'd like to keep the API as-is.  Thanks for the discussion!

**Pull request closed without merging**
