### PR TITLE
Do not require PermissionCallbacks

### PR DESCRIPTION
**Pull request by jaibatrik**
Fix for #19.

Made changes to `checkCallingObjectSuitability` to not require `PermissionCallbacks`. Placed `instanceof` checks for `PermissionCallbacks` in `requestPermissions` and `onRequestPermissionsResult` before calling `onPermissionsGranted` and `onPermissionsDenied`.

### CODE REVIEW

**Comment by jaibatrik** [comment]
I'll commit the documentation changes once we finalize the code changes. Thanks!

**Comment by samtstern** [comment]
@jaibatrik this change LGTM!  Let's go ahead and add the documentation as well.

**Comment by samtstern** [comment]
@jaibatrik documentation LGTM!  Going to merge and release a new version.

**Comment by samtstern** [comment]
Note that I used the 'squash and merge' so you'll likely have to rebase your fork if you plan to contribute to this repo in the future.

**Comment by samtstern** [comment]
Published version `0.1.9` with these changes.

**Comment by jaibatrik** [comment]
Thanks!

**Pull request merged**
